model:
  img:
    iniitial_dim: 128
    block_dims: [128, 196, 256]
    d_model: 256
    d_ffn: 256
    nhead: 8
    layer_names: ['self', 'cross'] * 4
    attention: 'linear'
    temp_bug_fix: True
    thr: 0.2
    border_rm: 2
    match_type: 'dual_softmax'  # options: ['dual_softmax, 'sinkhorn']
    dsmax_temperature: 0.1
    skh_iters: 3
    skh_init_bin_score: 0.1
    skh_prefilter: False
    train_coarse_percent: 0.2  # training tricks: save GPU memory
    train_pad_num_gt_min: 200  # training tricks: avoid DDP deadlock
    sparse_spvs: True  

  pcd:
    pretrain: ''
    arch: tdmatch_full
    node_id: -1
    num_layers: 4
    num_head: 4
    in_points_dim: 3
    first_subsampling_dl: 0.025
    conv_radius: 2.5
    in_feats_dim: 1
    final_feats_dim: 32
    intermediate_feats_dim: 32
    first_feats_dim: 128
    gnn_feats_dim: 256
    num_kernel_points: 15
    KP_extent: 2.0
    batch_norm_momentum: 0.02
    deform_radius: 5.0
    use_batch_norm: True
    fixed_kernel_points: center
    KP_influence: linear
    aggregation_mode: sum
    deformable: False
    modulated: False
    ape: False
    acn: True

  matching_coarse:
    thr: 0.2
    border_rm: 2
    match_type: 'dual_softmax'  # options: ['dual_softmax, 'sinkhorn']
    dsmax_temperature: 0.1
    skh_iters: 3
    skh_init_bin_score: 1.0
    skh_prefilter: false
    train_coarse_percent: 0.2  # training tricks: save gpu memory
    train_pad_num_gt_min: 200  # training tricks: avoid ddp deadlock
    sparse_spvs: True

  coarse:
    d_model: 256
    d_ffn: 256
    nhead: 8
    layer_names: ['self', 'cross'] * 4
    attention: 'linear' # options: ['linear', 'full']
    temp_bug_fix: True

  fine:
    fine.d_model: 128
    fine.d_ffn: 128
    fine.nhead: 8
    fine.layer_names: ['self', 'cross']
    fine.attention: 'linear'

optim:
  optimizer: ADAM
  lr: 0.0003
  weight_decay: 0.000001
  momentum: 0.98
  scheduler: ExpLR
  scheduler_gamma: 0.95
  iter_size: 4
  sinkhorn_iters: 100

data:
  dataset: tdmatch
  root: data/indoor
  voxel_size: 0.025
  augment_noise: 0.005
  pos_margin: 0.1
  overlap_radius: 0.0375
  train_info: configs/tdmatch/train_info.pkl
  val_info: configs/tdmatch/val_info.pkl
  benchmark: 3DLoMatch